### ISSUE TITLE
Pass back barView & dot instances on selection

### ISSUE THREAD

**Issue by terryworona** [Jawbone/JBChartView#118]
Currently, there is no way to access the bar view instance when a user selects the chart (we only have an index).

**Comment by gorbin** [comment]
Is there any chance that this feature will be released soon?

**Comment by terryworona** [comment]
Not likely. 

You can easily use the index to grab the bar view by exposing the views collection through a private category. 

When the functionality is added, it should be an easy switch over.

**Comment by terryworona** [comment]
I've thought about this a bunch. It would be trivial to add, but I'm not convinced it's the correct thing to do. 

I would rather than expose _mutable_ view instances to the caller. IMO they should remain private to the chart. 

A UITableView doesn't pass back view instances, but instead allows a caller to access a cell via cellForRowAtIndexPath. 

Perhaps that would be more appropriate? barViewAtIndex: and dotViewAtIndex: ?

**Comment by terryworona** [comment]
Added:
    - (UIView *)barViewAtIndex:(NSUInteger)index
    - (UIView *)dotViewAtHorizontalIndex:(NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex

This should help you out!
