### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kenthinson** [Jawbone/JBChartView#121]
Hello sorry for a noob question.
When I rotate the phone the chart no longer displays properly. 
So it looks like I need to call chart.reloadData()
but where is the best place to put that so it will happen every time the interface rotates?

**Comment by waterskier2007** [comment]
If you have the views in a view controller you could use the transition coordinators in iOS 8

-(void)willTransitionToTraitCollection:(UITraitCollection *)newCollection withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator
{
    [coordinator animateAlongsideTransition:^(id<UIViewControllerTransitionCoordinatorContext> animation) {
        [self.chartView reloadData];
    } completion:nil];
}
