### ISSUE TITLE
Crash when vertical value for horizontal at index x less than zero

### ISSUE THREAD

**Issue by sonbui-savvycom** [Jawbone/JBChartView#125]
Hi,
Inside my app, in some cases, the value for horizontal is less than zero and the chart will be crashed.
This is the assert: "Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'JBLineChartView // delegate function - (CGFloat)lineChartView:(JBLineChartView *)lineChartView verticalValueForHorizontalIndex:(NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex must return a CGFloat >= 0' "

How can I fix this error?

Thanks in advance.

**Comment by drichardson** [comment]
What was the reason for this being closed? I see the author calling NSAssert to explicitly prohibit negative vertical values, but I don't understand why since the code could calculate the height from the min/max whether they are negative or not.

**Comment by drichardson** [comment]
never mind, I found the other issues where this is explained
