### ISSUE TITLE
Overriding - (void)barChartView:(JBBarChartView *)barChartView didSelectBarAtIndex:(NSUInteger)index  is not showing selection view?

### ISSUE THREAD

**Issue by kidsid49** [Jawbone/JBChartView#133]
I override this method to take some action and then its stopped showing vertical selection view while on the other side avoiding overriding this view shows the vertical selection view.

**Comment by terryworona** [comment]
The demo works and it overrides didSelectBarAtIndex. Use that as a stepping stone to debug your issue. 

Make sure the chart's *showsVerticalSelection* property is YES. 

Sorry I can't help you without more details.

**Comment by kidsid49** [comment]
Fixed it. The view labels i am updating on the bar selection is having some autolayout constraint performance issue. Removed autolayout and vertical selection is showing again. In-fact the perfomance was so down there is delay in touches too.
