### ISSUE TITLE
Multiple colors to a line graph

### ISSUE THREAD

**Issue by knseir** [Jawbone/JBChartView#134]
Hello, 
Can one line have multiple colors ? I need to gradient-color my graph (higher values are green, lower ones are red...)
Is there a way to give a different color to every segment between two consecutive points base on the point's values ?
Thanks !

**Comment by terryworona** [comment]
Sorry, not at this time. Each line has to be a solid color as it's drawn as one continuous CGPath.

**Comment by nate50** [comment]
Any plans to add this capability in a future release?  And if not, do you think its even possible for me to hack together my own solution?  Thanks!

**Comment by terryworona** [comment]
Gradient lines are currently supported via:

    - (JBLineChartViewLineStyle)lineChartView:(JBLineChartView *)lineChartView lineStyleForLineAtLineIndex:(NSUInteger)lineIndex;

See the documentation (ie.JBLineChartView.h) for more information.

**Comment by nate50** [comment]
@terryworona  Sorry I was actually asking about using different colors for different segments, so that (similar to the example above) i could use green line segments for some values, and red line segments for others.  Is there any way at all to break the one continuous CGPath and make the line segment colors conditional?

**Comment by terryworona** [comment]
There doesn't exist an API in this library to do so. You'd have to get into the implementation and start messing around. 

Depending on your needs, you could just supply the chart with X number of lines, each one pertaining to a different color segment.
