### ISSUE TITLE
smallest value is shown as a blank bar

### ISSUE THREAD

**Issue by csmobile** [Jawbone/JBChartView#136]
In the current implementation of the JBBarChartView, the normalization of the data causes the lowest value in the data to be displayed as a blank bar.  Setting the min and max values does not seem to fix this. Is there some way to make the lowest, non-zero value draw a small bar in the chart, rather than none?

**Comment by terryworona** [comment]
This is normal. 

If you were to graph a set of data across a y-axis with it's origin at 0, and you had a value of 0 for one of the bars, it shouldn't show. 

As a hack you could just normalize your data to add + 1 to each point while keeping the chart's minimumValue = 0.
