### ISSUE TITLE
request: AreaChart - fillColorForLineAtLineIndex - add custom color for a specific X axis range

### ISSUE THREAD

**Issue by simonguertin** [Jawbone/JBChartView#137]
Hi, I love the chart!, I would like to be able to have the fill color of the chart be customizable for a specific X - axis range. Right now, The fill area is only 1 color. How could I achieve that ?

I was thinking to have another protocol method:

JBLineChartView * chart;
[chart setFillColor:[UIColor redColor] forRange:NSMakeRange(0,10)];
[chart setFillColor:[UIColor blueColor] forRange:NSMakeRange(10,30)];
[chart setFillColor:[UIColor purpleColor] forRange:NSMakeRange(40,100)];

Can this be added to the library ?

Regards,

Simon

**Comment by terryworona** [comment]
The area chart currently does not support multi-colors. 

We currently don't have any plans on incorporating such a feature into the library. 

It would be some-what challenging, as the chart's 'areas' are draw using a shape layer in core graphics. 

Hope this helps.
