### ISSUE TITLE
How can I group Bars?

### ISSUE THREAD

**Issue by jndefosse** [Jawbone/JBChartView#139]
Hi, thank you for this library. It's a great job.

I have a problem. How can I group bars?

Like this :

![zkvi1](https://cloud.githubusercontent.com/assets/5968328/6284301/d229a4cc-b8ee-11e4-8a4d-3e56dc467844.png)

**Comment by terryworona** [comment]
Sorry, the charting library does not support this kind of functionality. 

A few ideas on how to hack this (using the example above):

1. Create three separate charts; one for Chocolate, one for Vanilla and one for Strawberry. Create a master UIView that manages the layout of the three charts. 

2. Add 'fake' data between each of the groups (ie. bars with a value of 0)

3. Modify the library the directly to support groups (numberOfGroupsInChart:, barIndexForGroupIndex:), etc. This is clearly the most complicated version.
