### ISSUE TITLE
imports without pods

### ISSUE THREAD

**Issue by captainchung** [Jawbone/JBChartView#140]
A note for the docs, if you are not using pods, your imports should look like
#import "JBChartView.h"
#import "JBBarChartView.h"
#import "JBLineChartView.h"

**Comment by terryworona** [comment]
You only need to import either JBBarChartView or JBLineChartView, or both if you want to use two charts in one class. 

This is pretty explanatory and would be overkill to include. Leaving it out of docs for now.

**Comment by captainchung** [comment]
sure. i just wanted to point out the docs refer to the path where it's not needed. but no biggie.
#import "JBChartView/JBChartView.h"
#import "JBChartView/JBBarChartView.h"
#import "JBChartView/JBLineChartView.h"

**Comment by terryworona** [comment]
That's for a bridging header - it's not the same as a straight up import in objective-c land. 

Or I am missing something?

**Comment by captainchung** [comment]
here are 2 screenshots of my bridging header

![shot2](https://cloud.githubusercontent.com/assets/1685700/6498307/7e888c24-c29f-11e4-87ad-4db070586b34.png)
![shot1](https://cloud.githubusercontent.com/assets/1685700/6498308/7e8966b2-c29f-11e4-969c-22e40d02109e.png)

**Comment by terryworona** [comment]
Ah got it. Not sure why there was a JBChartView/ path in there. I've updated the README. Thanks.
