### ISSUE TITLE
The line fill color doesn't match the bottom of the drawn line

### ISSUE THREAD

**Issue by MobileVet** [Jawbone/JBChartView#146]
This is visible when the data includes 0 values, as seen in this image.
![screen shot 2015-03-12 at 10 43 28 am](https://cloud.githubusercontent.com/assets/1977118/6620996/5dbeaee0-c8aa-11e4-9a44-5e11476ba457.png)

**Comment by terryworona** [comment]
I can't reproduce this. 

Can you give me an example of data (vertical data points) you used to construct this chart? Are you setting any custom min/max values?

Attached is a screen of a fill chart with a 0 value. Looks normal?

![screen shot 2015-03-30 at 5 07 15 pm](https://cloud.githubusercontent.com/assets/358709/6909824/3bcffa92-d6ff-11e4-8ad6-d0473fca5307.png)

**Comment by markljones** [comment]
I have this as well. Maybe it has to do with the width of the line?
![screenshot 2015-04-01 15 31 29](https://cloud.githubusercontent.com/assets/2000791/6941966/4e622870-d884-11e4-90ff-5f6899452e25.png)

**Comment by terryworona** [comment]
Looks fine to me, no?

**Comment by markljones** [comment]
No ... The fill should extend to the left, right, and bottom edges of the view, but in those images (and the op) the fill does not reach the edge and there is white space. However, the line does reach the edge. I'll post an annotated image when I get a chance.

**Comment by terryworona** [comment]
Ah right. 

The fill layer uses the same path as the line layer. Thus, it will have left, right and bottom 'padding' equal to half the width of the line. 

This is a fairly complicated change and likely won't be addressed for some time. 

Making as enhancement.

**Comment by terryworona** [comment]
Alright, pretty confident I fixed this! 

Fills not go to the very edges of an era (leftmost x, rightmost x and bottom y).

**Comment by terryworona** [comment]
Screen attached of working example. 

![screen shot 2015-11-18 at 3 23 35 pm](https://cloud.githubusercontent.com/assets/358709/11257872/934910d0-8e09-11e5-9603-830ba095048b.png)

**Comment by MobileVet** [comment]
Thank you!
