### ISSUE TITLE
Pie Chart support

### ISSUE THREAD

**Issue by ZhenyuRipple** [Jawbone/JBChartView#149]
Hi, 

I am wondering why this library does not have pie chart support. 
Is there a plan to support it in the future?

**Comment by ericcgu** [comment]
Pie charts are poor poor way to present data.  Go with a bar chart instead. 

http://www.richardhollins.com/blog/why-pie-charts-suck/

**Comment by natanielw** [comment]
Hi I´d also like to see Pie Chart added.  I disagree that they´re always bad - to graphically tell a story around a punchy, simple stat they work quite well.
