### ISSUE TITLE
Crash when returning NAN

### ISSUE THREAD

**Issue by scooterschorschi** [Jawbone/JBChartView#150]
JBLineChartView from Master used.

From the doc:
'You can return NAN instead of CGFloat to indicate missing values.'
'Use: return [NSNumber numberWithFloat:NAN]'

This dos not compile. Function wants a CGFLoat as return value, not a NSNumber.

Returning NAN (Define) instead, results in a SIGSEGV.

**Comment by terryworona** [comment]
Sorry, it should be return [[NSNumber numberWithFloat:NAN] floatValue]

I've updated the .h

**Comment by scooterschorschi** [comment]
This also dos not work:

This (quick and dirty) example works:
------------------------------------------
- (CGFloat)lineChartView:(JBLineChartView *)lineChartView verticalValueForHorizontalIndex:(NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex
{
    if (lineIndex == 0)
    {
        long maxValue = [statCalc kmAtIndex: 0];
        return maxValue - [statCalc kmAtIndex: horizontalIndex]; // y-position (y-axis) of point at horizontalIndex (x-axis)
    }
    
    if (lineIndex == 1)
    {
        long maxValue = [statCalc kmAtIndex: 0];
        if (horizontalIndex == 0 || horizontalIndex == [statCalc count]) // first and last point
        {
            return maxValue - [statCalc kmAtIndex: horizontalIndex];
        }
        else
        {
            return maxValue - [statCalc kmAtIndex: horizontalIndex];
        }
    }
    return 0;
}
------------------------------------------

If I return NAN in else, it crashes
------------------------------------------
- (CGFloat)lineChartView:(JBLineChartView *)lineChartView verticalValueForHorizontalIndex:(NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex
{
    NSLog(@"lineIndex: %ld", (long)lineIndex);
    
    if (lineIndex == 0)
    {
        long maxValue = [statCalc kmAtIndex: 0];
        return maxValue - [statCalc kmAtIndex: horizontalIndex]; // y-position (y-axis) of point at horizontalIndex (x-axis)
    }
    
    if (lineIndex == 1)
    {
        long maxValue = [statCalc kmAtIndex: 0];
        if (horizontalIndex == 0 || horizontalIndex == [statCalc count]) // first and last point
        {
            return maxValue - [statCalc kmAtIndex: horizontalIndex];
        }
        else
        {
            return [[NSNumber numberWithFloat:NAN] floatValue];
        }
    }
    return 0;
}
------------------------------------------

Error log shows:
*** Assertion failure in -[JBLineChartView cachedMinHeight], /Users/schorsch/Documents/dev/iphone/mobiledev/SpritWatch/trunk/Classes/Classes/JBLineChartView.m:785
2015-04-02 10:57:19.813 SpritWatch[336:90b] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'JBLineChartView // delegate function - (CGFloat)lineChartView:(JBLineChartView *)lineChartView verticalValueForHorizontalIndex:(NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex must return a CGFloat >= 0'

**Comment by terryworona** [comment]
What version of the library are you using?

That exception trace should read 

    "Terminating .... must return a CGFloat >= 0 OR NAN"

Please pull the latest from master (v2.8.11), clean, and try again.

**Comment by scooterschorschi** [comment]
Hello

I donwloaded the master zip file two or three days ago. But I just checked the git master. There are a number of differences. So I think my source will work with your master version. I will try it later this evening. 

Best regards

**Comment by albixu** [comment]
Hello!

I have same problem.

I´m trying to paint a chart but I recive "app due to uncaught exception 'NSInternalInconsistencyException', reason: 'JBLineChartView // delegate function - (CGFloat)lineChartView:(JBLineChartView *)lineChartView verticalValueForHorizontalIndex:(NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex must return a CGFloat >= 0 OR NAN'" exception.

In this case, I need print negative value. Is it posible? I have v2.8.11 version.

Regards

**Comment by terryworona** [comment]
Hey @albixu,

The chart only supports positive values at the moment.

**Comment by albixu** [comment]
Is it posible that newer versions allow work with negative values?
