### ISSUE TITLE
Show chart selection permanently

### ISSUE THREAD

**Issue by va1da** [Jawbone/JBChartView#151]
Hi,
is there any way how to programaticaly set chart selection?
I want to always show selection and apropriate "detail" views with information about currently selected value.

Something like:
`- (void)setSelectedLineAtIndex:(NSUInteger)lineIndex horizontalIndex:(NSUInteger)horizontalIndex`

Thanks,
Ondra

**Comment by terryworona** [comment]
This functionality doesn't exit. It is being tracked in #153. 

I might get to implementing it within the next few weeks.

**Comment by va1da** [comment]
Great! Thanks for info.
