### ISSUE TITLE
Problems with selection when JBLineChartView is within UITableView

### ISSUE THREAD

**Issue by va1da** [Jawbone/JBChartView#155]
I can't reliably select and move in chart with pan gesture.
My JBLineChartView is embedded in UITableViewCell so I'm guessing that UITableView and JBLineChartView are fighting for the control over touches.

Is there any solution?
Thanks,
Ondrej

**Comment by terryworona** [comment]
Yes, they are in competition of touch events. 

It's recommended that you turn off userInteraction if you plan on using the charts in a table view. 

See here for an example of static charts used in tables: https://github.com/Jawbone/spark-friends-ios
