### ISSUE TITLE
Wrong calculation of the lineIndex 

### ISSUE THREAD

**Issue by buhtr** [Jawbone/JBChartView#157]
In function 
<code>(NSInteger)lineIndexForPoint:(CGPoint)point</code>
when touching is near the edge it calculates 
leftHorizontalIndex and rightHorizontalIndex as equal. After that leftLineChartPoint is equal rightLineChartPoint.

Hence, here 
<code>
CGFloat lineSlope = (CGFloat)(rightPoint.y - leftPoint.y) / (CGFloat)(rightPoint.x - leftPoint.x);
</code>
is division by zero with NaN.

Nevertheless,  function returns default selectedIndex which is "-1". In function  <code>(void)touchesBeganOrMovedWithTouches:(NSSet *)touches</code>
you have 
<code>
NSUInteger lineIndex = self.linesView.selectedLineIndex != kJBLineChartLinesViewUnselectedLineIndex ? self.linesView.selectedLineIndex : [self lineIndexForPoint:touchPoint];
</code>
So lineIndex is rather big and so the next line 
<code>if ([[self.chartData objectAtIndex:lineIndex] count] <= 0)</code>
we have an exception.

**Comment by terryworona** [comment]
Can you please post the entire exception stack trace + steps to reproduce.

**Comment by buhtr** [comment]
Hello, sorry for previous ugly comment I was in a bit of a rush, here is the exception 
<pre><code>
2015-04-16 08:45:50.131 JBChartViewDemo[84398:1895727] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104d84a75 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000104a1dbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000104c7c97e -[__NSArrayI objectAtIndex:] + 190
	3   JBChartViewDemo                     0x0000000102f888b9 -[JBLineChartView touchesBeganOrMovedWithTouches:] + 937
	4   JBChartViewDemo                     0x0000000102f89b1c -[JBLineChartView touchesBegan:withEvent:] + 828
	5   UIKit                               0x000000010342c980 forwardTouchMethod + 245
	6   UIKit                               0x00000001032fc9ce -[UIWindow _sendTouchesForEvent:] + 325
	7   UIKit                               0x00000001032fd493 -[UIWindow sendEvent:] + 683
	8   UIKit                               0x00000001032c9fb1 -[UIApplication sendEvent:] + 246
	9   UIKit                               0x00000001032d7227 _UIApplicationHandleEventFromQueueEvent + 17700
	10  UIKit                               0x00000001032b223c _UIApplicationHandleEventQueue + 2066
	11  CoreFoundation                      0x0000000104cb9c91 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	12  CoreFoundation                      0x0000000104cafb5d __CFRunLoopDoSources0 + 269
	13  CoreFoundation                      0x0000000104caf194 __CFRunLoopRun + 868
	14  CoreFoundation                      0x0000000104caebc6 CFRunLoopRunSpecific + 470
	15  GraphicsServices                    0x0000000107655a58 GSEventRunModal + 161
	16  UIKit                               0x00000001032b5580 UIApplicationMain + 1282
	17  JBChartViewDemo                     0x0000000102f74983 main + 115
	18  libdyld.dylib                       0x000000010563d145 start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
</code></pre>
I 've just loaded JBViewDemo 'Cycling Distance' in iOS's imitator in a high resolution and clicked near the edge of graph's frame (above SUN). 

By the way, the prev version works ok. It seems that the line 
<pre><code>CGFloat currentDistance = fabs(interesectionPoint.y - normalizedTouchPoint.y);</code></pre> 
makes sense. Here 'fabs' which returns NaN when interesectionPoint.y is NaN and thats why selectionIndex is never changed. In previous version was used 'abs' which, surprisingly, returns some valid value in this case.

Do you need any other information ?
