### ISSUE TITLE
gradient for bar chart is lost / sizing problem

### ISSUE THREAD

**Issue by ArminGrau** [Jawbone/JBChartView#158]
I'm trying to add a gradient to my bars, but it is not visible. 
The problem seems to be that at initialization time the bounds of the bar are not yet set (that comes later, in line 205 of JBBarChartView.m), so the gradient frame is always {0,0,0,0}.
Do you have an idea how to change this or work around it?
Thanks, Armin

Here's my code: 

    func barChartView(barChartView: JBBarChartView!, barViewAtIndex index: UInt) -> UIView! {
        let barView = BarChartBarView()
        ...
        return barView
    }

   class BarChartBarView: UIView {
    
    var gradient = CAGradientLayer()
    
    override init(frame: CGRect) {
        super.init(frame: frame)

        ...
        gradient.colors = [ UIColorFromRGB(0xF26E5E).CGColor, UIColorFromRGB(0xFD3968).CGColor]
        gradient.locations = [0.0 , 1.0]
        gradient.startPoint = CGPoint(x: 0.0, y: 0.0)
        gradient.endPoint = CGPoint(x: 1.0, y: 1.0)
        gradient.frame = self.bounds
        self.layer.insertSublayer(gradient, atIndex: 0)
    }
}

**Comment by terryworona** [comment]
Re-set your gradients frame in layout subviews.

    func layoutSubviews() 
    {
        gradient.frame = self.bounds
    }

**Comment by ArminGrau** [comment]
should have thought of that - thank you!
