### ISSUE TITLE
Bug when quickly tapping a line chart in two different places

### ISSUE THREAD

**Issue by nico75005** [Jawbone/JBChartView#159]
When I tap somewhere on a line chart (whether it's a long or short tap) and quickly after removing my finger I tap somewhere else, this is what happens:

![bug](https://cloud.githubusercontent.com/assets/1647328/7222406/58ba17de-e751-11e4-85a4-2dce17c38367.png)

**Comment by terryworona** [comment]
This is likely more to do with the demo code and less the core library. I'll look into it.

**Comment by f1rstattack** [comment]
I have created a demo project using your JBChartTooltipTipView , JBBarChartView and used - (void)setTooltipVisible:(BOOL)tooltipVisible animated:(BOOL)animated atTouchPoint:(CGPoint)touchPoint method in my viewcontroller.m same bug appears to me as well.
