### ISSUE TITLE
Small offset when using a footer for a x-axis

### ISSUE THREAD

**Issue by nico75005** [Jawbone/JBChartView#160]
I have noticed there is a tiny offset between the line chart (the red dotted one in my example) and the x-axis in the demo. I know the footer isn't part of the library but I cannot really say (as the offset is small) if it's a bug on the footer or on the chart itself so just in case...

![screenshot](https://cloud.githubusercontent.com/assets/1647328/7336514/fb02e05a-ec44-11e4-9fc5-962641bc2e5e.jpg)

**Comment by terryworona** [comment]
This is normal. That gap is equal to the half the width of the widest line in the chart. 

In this case, it's half the width of the white line. 

This padding is added to all sides of the chart, just after the header and footers.
