### ISSUE TITLE
white dot+dotted lines sometimes does not appear when touched.

### ISSUE THREAD

**Issue by kingsda** [Jawbone/JBChartView#161]
HI, 
Thanks for the elegant chart framework. In the line chart view, white dot+dotted line does not appear when touched at some points.

![whitedots](https://cloud.githubusercontent.com/assets/1458857/7348638/d350a0f2-ed10-11e4-9e37-9f5bfb90ff57.png)

**Comment by terryworona** [comment]
In the second screenshot you are selecting the rounded white line and not the dotted red one. 

From a touch point, the library determines the closest line to select based on distance.
