### ISSUE TITLE
Compare BarChart

### ISSUE THREAD

**Issue by Wildregar** [Jawbone/JBChartView#162]
Hi,
it's possible to implement a compare chart bar?
Maybe with a new datasource method : numberOfSection (?)

**Comment by terryworona** [comment]
I'm a bit confused as to what you mean. 

You want to compare to bar chart instances? ie:

    [barChart1.compare(barChart2)] 

?

**Comment by Wildregar** [comment]
No, this is an example: http://magoosh.com/gmat/files/2012/04/bar-charts-4.png

**Comment by terryworona** [comment]
Oh right. 

Anything is possible :) It's just not on the roadmap. Unlikely it would be built anytime soon. 

As a hack you can do this yourself by being clever with your datasource (ie. supply a 0-value bar for every index % 3 == 0).
