### ISSUE TITLE
XCode 6.3 with Swift 1.2 error

### ISSUE THREAD

**Issue by mitsus** [Jawbone/JBChartView#163]
Hi,
i'm try to use JBChart into my project with XCode 6.3 and Swift (1.2).
I've follow your installation tutorial and all work fine, but on my ViewController i've this error:

ChartViewController.swift:31:30: Cannot assign a value of type 'ChartViewController' to a value of type 'JBBarChartViewDelegate!'

and 

ChartViewController.swift:32:32: Cannot assign a value of type 'ChartViewController' to a value of type 'JBBarChartViewDataSource!'

This are the lines:

lineChart.delegate = self
lineChart.dataSource = self

Where are my errors?

Thanks a lot and congratulations for great job!

**Comment by terryworona** [comment]
Does your ChartViewController instance adhere to the line's datasource and delegate protocols?

**Comment by mitsus** [comment]
Yes Terryworona,
below the line:

class ChartViewController: UIViewController, JBLineChartViewDelegate, JBLineChartViewDataSource{

**Comment by terryworona** [comment]
The errors say JBBarChartViewDelegate and JBBarChartViewDataSource.

Note the 'Bar'. 

Are you sure your lineChart isn't an instance of JBBarChart?

**Comment by mitsus** [comment]
Ok, sorry for mistake, but during CTRL+drag JBLIneChart is not show.
I've added it manually and now on my ViewController i don't see errors, but when i launch on simulator it crashes with error:

libc++abi.dylib: terminating with uncaught exception of type NSException

![schermata 2015-04-28 alle 19 46 27](https://cloud.githubusercontent.com/assets/5763982/7376326/54321c54-eddf-11e4-9c78-ad319116063f.png)

**Comment by terryworona** [comment]
Please copy the entire stack trace, I can't see the origin of the problem from the screenshot.

**Comment by mitsus** [comment]
Below the stack trace:

2015-04-28 19:43:28.671 WeatherSpot[1350:46937] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'JBBarChartView // datasource must implement - (NSUInteger)numberOfBarsInBarChartView:(JBBarChartView *)barChartView'
*** First throw call stack:
(
	0   CoreFoundation                      0x02531746 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x03f32a97 objc_exception_throw + 44
	2   CoreFoundation                      0x025315da +[NSException raise:format:arguments:] + 138
	3   Foundation                          0x029a7720 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
	4   JBChart                             0x01720787 __28-[JBBarChartView reloadData]_block_invoke + 311
	5   JBChart                             0x0171fd3d -[JBBarChartView reloadData] + 525
	6   WeatherSpot                         0x0019995e _TFC11WeatherSpot19ChartViewController11viewDidLoadfS0_FT_T_ + 1918
	7   WeatherSpot                         0x00199b12 _TToFC11WeatherSpot19ChartViewController11viewDidLoadfS0_FT_T_ + 34
	8   UIKit                               0x02eb9da4 -[UIViewController loadViewIfRequired] + 771
	9   UIKit                               0x02eba095 -[UIViewController view] + 35
	10  UIKit                               0x02f09d2f -[UITabBarController transitionFromViewController:toViewController:transition:shouldSetSelected:] + 426
	11  UIKit                               0x02f0936f -[UITabBarController transitionFromViewController:toViewController:] + 64
	12  UIKit                               0x02f0552b -[UITabBarController _setSelectedViewController:] + 339
	13  UIKit                               0x02f053ae -[UITabBarController setSelectedViewController:] + 193
	14  UIKit                               0x02f09248 -[UITabBarController _tabBarItemClicked:] + 338
	15  libobjc.A.dylib                     0x03f487cd -[NSObject performSelector:withObject:withObject:] + 84
	16  UIKit                               0x02d56a90 -[UIApplication sendAction:to:from:forEvent:] + 99
	17  UIKit                               0x02d56a22 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
	18  UIKit                               0x030b174d -[UITabBar _sendAction:withEvent:] + 466
	19  libobjc.A.dylib                     0x03f487cd -[NSObject performSelector:withObject:withObject:] + 84
	20  UIKit                               0x02d56a90 -[UIApplication sendAction:to:from:forEvent:] + 99
	21  UIKit                               0x02d56a22 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
	22  UIKit                               0x02e9718a -[UIControl sendAction:to:forEvent:] + 69
	23  UIKit                               0x02e975a7 -[UIControl _sendActionsForEvents:withEvent:] + 598
	24  UIKit                               0x02e971c2 -[UIControl sendActionsForControlEvents:] + 48
	25  UIKit                               0x030b66e0 -[UITabBar(Static) _buttonUp:] + 123
	26  libobjc.A.dylib                     0x03f487cd -[NSObject performSelector:withObject:withObject:] + 84
	27  UIKit                               0x02d56a90 -[UIApplication sendAction:to:from:forEvent:] + 99
	28  UIKit                               0x02d56a22 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
	29  UIKit                               0x02e9718a -[UIControl sendAction:to:forEvent:] + 69
	30  UIKit                               0x02e975a7 -[UIControl _sendActionsForEvents:withEvent:] + 598
	31  UIKit                               0x02e96811 -[UIControl touchesEnded:withEvent:] + 660
	32  UIKit                               0x02daecfa -[UIWindow _sendTouchesForEvent:] + 874
	33  UIKit                               0x02daf7d6 -[UIWindow sendEvent:] + 792
	34  UIKit                               0x02d6d6d1 -[UIApplication sendEvent:] + 242
	35  UIKit                               0x02d7db08 _UIApplicationHandleEventFromQueueEvent + 21484
	36  UIKit                               0x02d51337 _UIApplicationHandleEventQueue + 2300
	37  CoreFoundation                      0x0245306f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	38  CoreFoundation                      0x02448b7d __CFRunLoopDoSources0 + 253
	39  CoreFoundation                      0x024480d8 __CFRunLoopRun + 952
	40  CoreFoundation                      0x02447a5b CFRunLoopRunSpecific + 443
	41  CoreFoundation                      0x0244788b CFRunLoopRunInMode + 123
	42  GraphicsServices                    0x063ad2c9 GSEventRunModal + 192
	43  GraphicsServices                    0x063ad106 GSEventRun + 104
	44  UIKit                               0x02d55106 UIApplicationMain + 1526
	45  WeatherSpot                         0x001325e4 main + 180
	46  libdyld.dylib                       0x049f2ac9 start + 1
	47  ???                                 0x00000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by terryworona** [comment]
The error is right at the top of the trace:

    JBBarChartView // datasource must implement - (NSUInteger)numberOfBarsInBarChartView:(JBBarChartView )barChartView
