### ISSUE TITLE
Will JBChartView integrated with React Native?

### ISSUE THREAD

**Issue by yuanyong** [Jawbone/JBChartView#164]
Will JBChartView provider the API to easily integrated with React Native?

@terryworona

**Comment by terryworona** [comment]
We have no plans to support integrations with with React Native. Sorry.

**Comment by myusuf3** [comment]
I have got something working with react native and jbchartview. I will see if I can make a stand alone package if that is cool with @terryworona . I am not sure when since its internal project but it is possible.
