### ISSUE TITLE
Not All Data Points Visible in Flexible View

### ISSUE THREAD

**Issue by cliftonlabrum** [Jawbone/JBChartView#166]
I have a `JBLineChartView` that has Auto Layout constraints that make its width change depending on the device size. It's implemented inside a `UITableViewCell`.
![al](https://cloud.githubusercontent.com/assets/2513753/7641431/8c728b6a-fa3e-11e4-885b-2a041b7fba7a.png)

This particular line chart has 11 data points. I call `reloadData()` inside `cellForRowAtIndexPath`. The graph appears, but when it's in portrait mode, it only shows 5 of the datapoints.

![port](https://cloud.githubusercontent.com/assets/2513753/7641479/da4a1326-fa3e-11e4-9387-4c1829077d57.png)

But if I rotate to landscape, then scroll the table cell off the screen then back on (so it calls `cellForRowAtIndexPath` again, and thus `reloadData()`, it shows *all* the data points:

![land](https://cloud.githubusercontent.com/assets/2513753/7641553/5486ab0e-fa3f-11e4-8459-71cadfd76c25.png)

Am I calling `reloadData()` in the right place? The line chart doesn't seem to fit the data points to the current frame of the `JBLineChartView` in portrait.

**Comment by terryworona** [comment]
Try printing out the bounds of the chart view in different orientations. 

It's unlikely the line is being drawn outside of the bounds of the chart. It's more likely that your chart's bounds are going outside the frame of the table cell. 

Also look at https://github.com/Jawbone/spark-friends-ios to see how a chart can adapt to changing orientations.

**Comment by cliftonlabrum** [comment]
Thanks for your quick response. I have reload my table (with its attendant graph reloads) on `viewWillTransitionToSize` after rotating to landscape and then back to portrait, the graph gets re-drawn and looks correct. There's something about the initial portrait view where the graph is getting rendered before the layout calculations of the table cell are done.

I looked at the Spark Friends app, and it doesn't appear to redraw the graphs on orientation change. They seem to have a fixed width.

**Comment by cliftonlabrum** [comment]
It turns out I needed to call `cell.contentView.layoutIfNeeded()` right before calling `reloadData()` since the cell's contentView wasn't laid out properly yet.
