### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by jathu** [Jawbone/JBChartView#167]
I get this error on a Swift project, building for iOS7:

```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_JBLineChartView", referenced from:
      __TMaCSo15JBLineChartView in GraphController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have a bridging file and included it in the build settings (projectname-bridging-header.h). Is there a solution to this? The error logs don't provide much detail.

**Comment by terryworona** [comment]
Definitely looks as if your GraphController can't find the JBLineChartView implementation (.m). I assume the .h import compiles fine?

Are you adding the library via a pod? Are you opening the workspace up instead of the project file?

Nice avatar btw!

**Comment by jathu** [comment]
I manually included the library. Dragged the folder into the project, I see the files references work. I tried linking the .m files under ```Build Phases -> Compile Sources```, however the .m files do not show up. I'm not sure what you mean by opening the workspace instead of the project file (I'm new to iOS dev).

Thanks, can never go wrong with DOOM!

**Comment by terryworona** [comment]
Did you drag the .m files into Build Phases -> Compile Sources? That should do it. 

There's a few things that could go wrong with all of this (manual copied files). Namely, you won't get any future patches or bugs fixes without manually re-cloning and copying. 

I recommend using cocoapods for dependency management. Check it over at https://cocoapods.org/ and follow the instructions to add the JBChartView pod. 

Sorry I can't be of more help, but the question isn't so much related to JBChartView but more using libraries & Xcode configuration in general. Closing for now.
