### ISSUE TITLE
Line color overlap issue

### ISSUE THREAD

**Issue by Dids** [Jawbone/JBChartView#168]
Any ideas on what's causing a line color overlapping issue such as in the image below?

![JBChartView line color overlap issue](http://oi62.tinypic.com/mkukxd.jpg)

**Comment by terryworona** [comment]
Ah looks to be a bug. 

Does this happen only after a selection or right away without any touch events?

**Comment by Dids** [comment]
Right away, and if I'm not mistaken it might also happen when the colors overlap the other way around. Not 100% sure on that one though.
If it helps, the color/line order is: blue, green, orange.

**Comment by Dids** [comment]
There colors I'm using are as follows
```objc
[UIColor colorWithHue:0.55 saturation:0.87 brightness:0.99 alpha:1];
[UIColor colorWithHue:0.32 saturation:0.47 brightness:0.77 alpha:1];
[UIColor colorWithHue:0.06 saturation:0.82 brightness:1 alpha:1];
```

For now, I'm trying to draw a clearColor line for each of the line indexes, see if that helps, since the fill color seems to be working just fine.

**Comment by terryworona** [comment]
Super odd. 

In short, each fill line contains a stroke layer and a filler layer. It really needs to only include the fill layer, not sure why it was done this way. 

Anyways, each of the two layers are added in sequence as sublayers. So each separate line's stroke and fill are added in order. There shouldn't be any mis-ordering of the layers. Very weird. 

I'll take a peak when I have some time...

**Comment by Dids** [comment]
The only issue I see with setting the line color to [UIColor clearColor] (when using a fill color) is that the bottom line (ie. "zero line") disappears.

**Comment by terryworona** [comment]
Looked at this over the weekend. I could not reproduce. Are you able to reproduce this in any way with the existing demo app? If so, how, and what modifications can I make to do so?

**Comment by Dids** [comment]
I'll see if I can whip up a simple test project, or modify the demo. I'll try to do that tonight. :)

**Comment by Dids** [comment]
Sorry, haven't had any time to create a minimal project that reproduces this.
