### ISSUE TITLE
Charts not rendering properly

### ISSUE THREAD

**Issue by AlexChesters** [Jawbone/JBChartView#171]
Hi, I've been using this library and I've noticed that on first appearing the charts don't seem to draw properly.
![ios simulator screen shot 31 may 2015 15 24 21](https://cloud.githubusercontent.com/assets/10558792/7902207/3df85514-07a9-11e5-8a2d-2d192ebcb5d2.png)
Then after navigating to another view and back it draws correctly
![ios simulator screen shot 31 may 2015 15 24 25](https://cloud.githubusercontent.com/assets/10558792/7902210/51524e3a-07a9-11e5-9e23-94c2c016f300.png)

Do you have any ideas?
Thanks

**Comment by terryworona** [comment]
Are you calling reload data after a proper frame has been set?

**Comment by AlexChesters** [comment]
I call it each time in my viewDidAppear

Also I now realise it is not a specific iPhone 4S issue

**Comment by AlexChesters** [comment]
Solved this issue by re-adding these lines:
```
-(void)setFrame:(CGRect)frame
{
    [super setFrame:frame];
    
    // because frame is set early, we may not have sources
    if (self.delegate != nil && self.dataSource != nil)
    {
        [self reloadData]; // reload all subviews on frame change
    }
}
```

To the JBChartView.m
