### ISSUE TITLE
Is there anyway to plot two vertical values for one horizontal index in the bar chart?

### ISSUE THREAD

**Issue by dppeak** [Jawbone/JBChartView#172]
I want to be able to plot two vertical values for a particular day when using JBBarChartView.  Am I missing something already present, or can this be added?  Thanks!

**Comment by terryworona** [comment]
Currently, this is not possible (within the same line). 

I'm not sure what style your chart is, but this may be a solution if you're doing scatterplots:

Supply two lines:

    - (NSUInteger)numberOfLinesInLineChartView:(JBLineChartView *)lineChartView
    {
        return 2;
    }

Then return two separate values for the same day:

    - (CGFloat)lineChartView:(JBLineChartView *)lineChartView verticalValueForHorizontalIndex:  (NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex
    {
        // first line, Monday
        if (lineIndex == 0 && horizontalIndex == 0) 
            return 10

        // second line, Monday
        else if (lineIndex == 1 && horizontalIndex == 0)
            return 20

    }

Hope this helps

**Comment by dppeak** [comment]
I'm using barChart View.

Here's an example of what I'm looking to do.

![example](https://cloud.githubusercontent.com/assets/868044/7919622/32467bc2-085f-11e5-9851-3cd44359978b.png)

**Comment by terryworona** [comment]
Oh, bar chart. Sorry, I misunderstood. 

You can supply custom UIView's for each bar via 

    - (UIView *)barChartView:(JBBarChartView *)barChartView barViewAtIndex:(NSUInteger)index

Just break each custom view into 2 seconds (using subviews, sublayers, etc). The math and size of each colored section are left up to you.

**Comment by dppeak** [comment]
I was thinking along those lines, but wasn't sure about the setting of the selection color for the "subview".  May just have to an alpha for the subview and let the darkening of the main color be enough.  Thanks for the help.
