### ISSUE TITLE
Semantic issue

### ISSUE THREAD

**Issue by sunu45** [Jawbone/JBChartView#173]
hi all,
I have been using jbchartview in my swift project and was working well untill i updated xcode to version 6.3. Now it gives semantic issue which says:

Auto property synthesis will not synthesize property 'dataSource'; it will be implemented by its superclass, use @dynamic to acknowledge intention.

what actually is the problem and how to solve it.
Thanks in advance

**Comment by terryworona** [comment]
What version of the library are you using. This should be fixed as as version [2.8.14](https://github.com/Jawbone/JBChartView/tree/v2.8.14) via commit:d299cd6e7e76b7c6580dfc1dfa87c7d377db087f
