### ISSUE TITLE
JBLineChartView: wrong width on iPhone6/6+

### ISSUE THREAD

**Issue by va1da** [Jawbone/JBChartView#177]
I have JBLineChartView inside UITableViewCell which is inserted in UITableView after the touch on another UITableViewCell.
When the cell is displayed for the first time it has wrong width on iPhone6/6+. Later it look OK.
If I put ordinary UIView instead of JBLineChartView everything works fine.

Any idea what could be the reason?

Thanks.

![bad](https://cloud.githubusercontent.com/assets/961352/8649692/ebada15c-296c-11e5-8b91-7f883fde57d8.png)
![ok](https://cloud.githubusercontent.com/assets/961352/8649694/ebde05f4-296c-11e5-8f62-489a3d842556.png)

**Comment by terryworona** [comment]
I'm guessing the width of the chart is incorrect when it's displayed the first time.

As an experiment, keep an instance around of the chart and call reloadData on viewDidAppear of your table controller. See what happens...

**Comment by va1da** [comment]
Unfortunately I can't because the big cell with the chart is made visible only after I select some row :-(

**Comment by va1da** [comment]
I've created a small sample which demonstrates the problem: https://dl.dropboxusercontent.com/u/102474509/ChartCellTest.zip

**Comment by terryworona** [comment]
I'm not super familiar with auto layout and constraints, but it seems that the chart's width is equal to 600 when the table is first loaded. 

The property is found in IB:

![screen shot 2015-07-13 at 9 55 56 am](https://cloud.githubusercontent.com/assets/358709/8655285/f7b05648-2944-11e5-9a08-16b861052045.png)

**Comment by va1da** [comment]
AL constraints are set correctly, so it should work.
If you replace JBLineChartView with UIView it works OK.
So I think there must be something about JBLineChartView.

**Comment by terryworona** [comment]
Print out the chart's frame on reloadData and it's grabbing 600. 

Subsequent call have it set to 375. 

![screen shot 2015-07-13 at 10 12 22 am](https://cloud.githubusercontent.com/assets/358709/8655610/2f219eb4-2947-11e5-8590-a854edff70b8.png)

The chart is doing it's thing, it's just that reloadData is being called at a time where the chart's size isn't correctly set. 

Why is it 600 to begin with? Any way to correct this and have it equal the width of the container?

**Comment by va1da** [comment]
I thought that AL should do it.
But I don't know how to make AL perform its calculations before reloadData is called :-(
I've tried to call layoutIfNeeded and layoutSubviews but it doesn't work.

**Comment by va1da** [comment]
OK finally I figured it out. I had to implement layoutSubviews:

- (void)layoutSubviews
{
    [super layoutSubviews];
    
    CGRect frame = self.contentView.frame;
    CGRect chartFrame = self.lineChartView.frame;
    chartFrame.size.width = frame.size.width;
    self.lineChartView.frame = chartFrame;
    [self.lineChartView reloadData];
}

**Comment by ericcgu** [comment]
Isn't it `viewWillLayoutSubviews`
