### ISSUE TITLE
Ability to get a points frame in the didSelectLineAtIndex method

### ISSUE THREAD

**Issue by crobertsbmw** [Jawbone/JBChartView#178]
In the line graph, I want to enlarge the data point when someone clicks on it. I was thinking I could just add a view on top of the existing point, but I have no idea what the coordinates of that point are. Maybe there is already a way to do this that I am missing?

**Comment by terryworona** [comment]
You could keep a reference a custom dot view in your controller:

    - (UIView *)lineChartView:(JBLineChartView *)lineChartView dotViewAtHorizontalIndex:(NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex
    {
        self.dotView = ....
        return self.dotView
    }

Then:

    - (void)lineChartView:(JBLineChartView *)lineChartView didSelectLineAtIndex:(NSUInteger)lineIndex horizontalIndex:(NSUInteger)horizontalIndex touchPoint:(CGPoint)touchPoint
    {
        [self.dotView enlarge];
    }

And:

    - (void)lineChartView:(JBLineChartView *)lineChartView didDeselectLineAtIndex:(NSUInteger)lineIndex horizontalIndex:(NSUInteger)horizontalIndex touchPoint:(CGPoint)touchPoint
    {
        [self.dotView compress];
    }

**Comment by crobertsbmw** [comment]
Thanks, I think that will work. I guess I didn't read the documentation close enough.
