### ISSUE TITLE
Vertical values should be supplied by the DataSource delegate for LineCharts

### ISSUE THREAD

**Issue by sdjm-tessella** [Jawbone/JBChartView#180]
At the moment, the `JBLineChartViewDelegate` provides the method `- (CGFloat)lineChartView:(JBLineChartView *)lineChartView verticalValueForHorizontalIndex:(NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex` but this should be the responsibility of the `JBLineChartViewDataSource`

**Comment by terryworona** [comment]
Yeah, I noticed this too. Decided to leave it as I don't want to break the interface. 

Saving it for 3.0 perhaps.

**Comment by terryworona** [comment]
Closing for now since this technically follows the same pattern as UITableView. 

For 3.0, if we decide to re-master the interface, we will move such functions from the delegate into the dataSource.
