### ISSUE TITLE
JBLineChart reloadData problem

### ISSUE THREAD

**Issue by emergencyhug** [Jawbone/JBChartView#181]
I set a JBLineChartView on an UIScrollView,
the line chart showed up and worked fine after the first [linechart reloadData];
but if I scrolled the view for more than 2 or 3 times it crashed and threw me this exception:
- - - - - 
*** Assertion failure in -[JBLineChartView padding], /...MyApp/Pods/JBChartView/Classes/JBLineChartView.m:455
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'JBLineChartView // dataSource must implement - (NSUInteger)numberOfLinesInLineChartView:(JBLineChartView *)lineChartView'
*** First throw call stack:
(0x186c282d8 0x1983fc0e4 0x186c28198 0x187adced4 0x10005b6f0 0x100061f90 0x18b7ffd8c 0x18b69c8f8 0x18b695f68 0x18b66918c 0x18b90a324 0x18b6676a0 0x186be0240 0x186bdf4e4 0x186bdd594 0x186b092d4 0x1903276fc 0x18b6cefac 0x10003b46c 0x198a7aa08)
libc++abi.dylib: terminating with uncaught exception of type NSException

I did add 
if (!self.dataSource){
   NSLog(@"nil datasource");
}
- - - - -
and it showed that dataSource was nil when I scrolled away and back on the line chart... which caused the crash issue.
Not sure about other kind of chart but this is how far I reach it. Thanks for any help and the nice work of JBChartView!

---
EDIT
---
It seemed not caused by any scroll but by directly tap on the chart.... I'm trying to figure it out and will edit this issue soon.

**Comment by terryworona** [comment]
It sounds like your datasource is being dealloc'd in some way. Doesn't sound to be an internal issue with the chart library, but rather how your managing the chart's delegation. 

Step through the code again and see how your managing the chart's .datasource and .delegate. Watch for nil's!

**Comment by emergencyhug** [comment]
Thanks for reply and please check the update.
