### ISSUE TITLE
Limit touches passing to parent view

### ISSUE THREAD

**Issue by penaeric** [Jawbone/JBChartView#184]
I have a cool chart in a view controller that is hosted on a UIPageViewController.  Whenever you start swiping over the chart (to see the tooltip) the page controller takes over.  
I've been trying to figure out how to prevent my JBChartView view to pass touches to the view controller/page controller but I've had no success.
Any suggestions?

**Comment by terryworona** [comment]
Both the JBChartView and UIPageViewController instance can't share the same swipe gesture. 

I suggest removing any selection functionality such that the page controller can do it's thing. 

This should help:

    self.chartView.userInteractionEnabled = NO;;
