### ISSUE TITLE
Disabling/Enabling certain functionality: line chart selection and x-axis values

### ISSUE THREAD

**Issue by swl367** [Jawbone/JBChartView#185]
Hello, I currently have the kJBLineChartLinesViewDefaultDimmedOpacity constant set to 1.0f so that my non-selected line views won't fade away when i'm dragging the graph. Is there a specific way to do this without changing that constant?

Also, I would like to see labels on the x-axis. Is that possible?

Thanks!

**Comment by swl367** [comment]
I've figured out using the footerview that i can make my own x axis, but I'm still wondering if there's a solution to remove the dim without changing the opacity value.

**Comment by terryworona** [comment]
There is currently no way to configure the opacity value of dimmed lines on selection. 

The only way is to modify the constant (what you are already doing). 

We can expose something via the datasource:

    - (BOOL)lineChartView:(JBLineChartView *)lineChartView shouldDimLineOnSelectionAtHorizontalIndex:(NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex;

Would that work?

**Comment by swl367** [comment]
@terryworona yup that'd work. thanks.

**Comment by terryworona** [comment]
Added to JBLineChartDataSource:

    - (CGFloat)lineChartView:(JBLineChartView *)lineChartView dimmedSelectionOpacityAtLineIndex:(NSUInteger)lineIndex;
