### ISSUE TITLE
Partially filled bar

### ISSUE THREAD

**Issue by iDevelopper** [Jawbone/JBChartView#186]
Hello,

How can i partially fill a bar ?

Like this ;

![barsample](https://cloud.githubusercontent.com/assets/1782450/9870081/40814208-5b89-11e5-86ea-58856b557b84.png)

**Comment by terryworona** [comment]
Yes, totally possible - but requires a bit of work. 

You'll have to supply a custom UIView for each bar via: 

    - (UIView *)barChartView:(JBBarChartView *)barChartView barViewAtIndex:(NSUInteger)index

Then, customize each bar by drawing only certain components (ie. red, green, etc). 

Hope this helps.

**Comment by iDevelopper** [comment]
Thank you very much !

I had a doubt about this :

 *  @return A UIView subclass. The view will automatically be resized by the chart during creation (ie. no need to set the frame).

**Comment by terryworona** [comment]
Yeah, the bar's width and height will be automatically resized to correlate with the chart's frame and number of data points. 

You're custom UIView should be able to lay itself out with any kind of frame.

**Comment by iDevelopper** [comment]
Ok, I see, thank you
