### ISSUE TITLE
Needs to support negative values

### ISSUE THREAD

**Issue by roksollc** [Jawbone/JBChartView#189]
Our data oscillates (line SIN) between positive and negative values, including 0. This library will not work, because it insists that data MUST be > 0 or NAN. This is the very first time I've ever found a charting tool that has such limitations.

**Comment by terryworona** [comment]
The chart is limited on purpose - it's not intended to be super robust, but rather stable, simple and easy to implement. 

I would recommend another, more elaborate charting library, such as core plot (https://github.com/core-plot/core-plot). 

You could technically use JBChartView if you normalized your data to be > 0. Visually, it would look the same.

**Comment by iDevelopper** [comment]
+1
