### ISSUE TITLE
Show data above each column  

### ISSUE THREAD

**Issue by tuanphamanh91** [Jawbone/JBChartView#194]
Hello, 
Is there the way to show data above each column like this:
![img_0182](https://cloud.githubusercontent.com/assets/4038168/12261553/5a247da0-b954-11e5-8e8b-de90623f9fd1.PNG)

Please help me, sorry about my English. Thank you so much!

**Comment by terryworona** [comment]
Anything is possible :)

The chart API does not expose this functionality natively. 

Either fork the repo, and add custom labels to each bar via a new delegate function:

    - (NSString *)labelForBarAtIndex:(NSUInteger)index;

Or, leave the library alone, and supply a custom UIView bar with a label on top via:

    - (UIView *)barViewAtIndex:(NSUInteger)index;

TL;DR - not possible, but not hard to accomplish with a bit of custom code.

**Comment by tuanphamanh91** [comment]
Thank you for your quick reply! I will try the way as you say! Have a nice day ^_^
