### ISSUE TITLE
Many Line Charts in Table View

### ISSUE THREAD

**Issue by Hadjimina** [Jawbone/JBChartView#198]
Heyo guys 
First of all : Awesome Project :+1: 
However I have run into a problem. I use your Line Charts in a Tableview where each row should have its own line Chart. This gets rather laggy. Any idea on fixing this ?
(I am reusing cell btw.)

Thanks for your input

**Comment by terryworona** [comment]
Go ahead and check out this demo project -> https://github.com/Jawbone/spark-friends-ios

How many cells are in your table? How often are you calling reload? etc.

**Comment by Hadjimina** [comment]
There are about 40 Graphs. I'll check tomorrow how often they get reloaded. 
Thanks for your suggestion. Will check it out.

**Comment by terryworona** [comment]
Cool!

**Comment by Hadjimina** [comment]
So i got down to it : 
i've got 7 line per graph and i think the amount of line per graph is the problem.
The reason I need so many lines is i want to have a line for every Y-value. Is there a way to achieve that without causing the table to lag ?
