### ISSUE TITLE
Not able to create Y-Axis labels or background grid

### ISSUE THREAD

**Issue by pkasson** [Jawbone/JBChartView#20]
Is it possible to add a Y-Axis that shows X-Axis values and a background grid ?

**Comment by monish152** [comment]
i have been able to create a line chart with x axis labels. I want to create y axis labels like attached screenshot. can anyone please help.
![renderedimage](https://cloud.githubusercontent.com/assets/1301491/18746682/71087378-80e6-11e6-9da4-153cff20b201.jpg)

**Comment by terryworona** [comment]
There is still no functionality in the library for a y-axis. As originally stated, you can simply create a subview representing the y axis visuals and insert it below a transparent chart view.
