### ISSUE TITLE
Cannot change bar colors after initial load

### ISSUE THREAD

**Issue by erikackermann** [Jawbone/JBChartView#201]
1. Setup a chart and implement `-barChartView:colorForBarViewAtIndex:` to return a UIColor for each bar.
2. Change this color to a different UIColor and call `reloadData` on the chart.
3. Bar colors are unchanged; still show color set in step 1.

The color does not update.  It appears that the changes added with `reloadDataAnimate:` have broken this functionality and initial colors set for each bar no longer change when table reloads.

**Comment by terryworona** [comment]
Ah good catch. Sorry about that. I'll look into this later today.

**Comment by terryworona** [comment]
Fixed via commit: 0b603cde1f463e0cf56264aec0be9d2c92814658

Tag: [v.3.0.8](https://github.com/Jawbone/JBChartView/tree/v3.0.8)

I reverted my previous reloadDataAnimated: changes that were causing the issue. I'd rather deal with performance issues with huge datasets than it not work altogether. I'll continue to investigate the non-animated performance issues .
