### ISSUE TITLE
ability to set line chart view padding

### ISSUE THREAD

**Issue by dam13n** [Jawbone/JBChartView#205]
Having the padding set automatically can give an odd look, such as a gradient fill that shows for zero values. Would be sweet to enable setting the value ourselves.

**Comment by terryworona** [comment]
Can you be more specific on 'padding'?

There is a bunch of padding :)

Screenshot would help.

**Comment by dam13n** [comment]
For sure! In my case, I have a gradient fill for a line that is clear but that I show dots for. So padding is set based off those, and results in the gradient fill showing for zero values (you can see some fill above the white line in the first screenshot.

Another issue, and I know this is getting very specific to my use case, is that the drawn line is offset too and results in a mismatched overlap (first screenshot). Makes sense to do this normally b/c you don't want your line clipped out of the chart, but for me, I want to show the line at it's true (vertical) value, so I don't clip to bounds and force the padding to zero (second screenshot).
```
// JBLineChartView.m
- (CGFloat)padding
  ...
  return (maxLineWidth * 0.5);
```

![simulator screen shot mar 23 2016 6 49 22 pm](https://cloud.githubusercontent.com/assets/6476222/14006188/0c1d7a38-f128-11e5-9585-bc071f0a907e.png)

```
- (CGFloat)padding
  ...
  return (0.0);
```
![simulator screen shot mar 23 2016 6 48 20 pm](https://cloud.githubusercontent.com/assets/6476222/14006190/10e8f34e-f128-11e5-85e7-cdc2071b0122.png)

**Comment by terryworona** [comment]
Sorry I'm having a difficult time understanding your case. I've read it over several times, and I'm still at a loss. 

It sounds like you've figured out a solution for yourself though. 

My suggestion is to either fork the repository and make edits to the core lib, or, subclass JBLineChartView and override the padding property (via a privately defined category -- google it if you're unaware of this technique). 

Hope this helps.
