### ISSUE TITLE
Not able to change the color of linechart  with custom color

### ISSUE THREAD

**Issue by georgek1991** [Jawbone/JBChartView#208]
I am using the function
- (UIColor *)lineChartView:(JBLineChartView *)lineChartView colorForLineAtLineIndex:(NSUInteger)lineIndex 
{
    if (lineIndex == 0) {
        return [UIColor colorWithRed:242.0f green:110.0f blue:98.0f alpha:1.0f];
    }
    return [UIColor blueColor];//[UIColor colorWithRed:83.0f green:125.0f blue:248.0f alpha:1.0f];
}

when i give a custom color like above it does not take the value and instead show white color but when i give default color like blueColor it works perfectly.
I think it is a bug or Am I doing something wrong?

**Comment by youvalv** [comment]
you forgot to divide by 255.0f
return [UIColor colorWithRed:242.0f/255.0f green:110.0f/255.0f blue:98.0f/255.0f alpha:1.0f]
