### ISSUE TITLE
[question] Does JBChartView support logarithmic scale?

### ISSUE THREAD

**Issue by dodikk** [Jawbone/JBChartView#211]
I need to implement a scatter plot with a **logarithmic Y axis scale**
See the link for details.
https://gist.github.com/dodikk/dbad6675a7ead2d322ced451495cac09

Is it feasible to use JBChartView?

P.S. I have not found any answers on Google, StackOverflow, etc.

**Comment by terryworona** [comment]
The library supports dots and solid/dashes lines out of the box. 

The log scale is also fine - so long as your data model represents a log function. 

The library is written in Objective C, so no worries there. It also has a bridging header for Swift integration. 

The custom axis and background grids are also possible - but you'll have to spin that up yourself by subclassing the chart instance and poking around. It will require some work. 

Hope this helps.

**Comment by dodikk** [comment]
@terryworona , thanks for the reply.

> The log scale is also fine - so long as your data model represents a log function.

I have not quite understood this point. Could you, please explain the approach with more details?
I have not found a log scale axis class. For example, [shinobi](https://www.shinobicontrols.com/docs/ShinobiControls/ShinobiCharts/2.8.7/Premium/Normal/html/Classes/SChartLogarithmicAxis.html) has one. 

Thanks in advance.

**Comment by terryworona** [comment]
The y-axis will normalize itself across whatever data model you have. 

So, if that model is a log(x) function, it will render fine. Check out the demo project and just change:

    - (CGFloat)lineChartView:(JBLineChartView *)lineChartView verticalValueForHorizontalIndex:(NSUInteger)horizontalIndex atLineIndex:(NSUInteger)lineIndex
    {
        return log(horizontalIndex);
    }
