### ISSUE TITLE
Does not conform with protocol

### ISSUE THREAD

**Issue by jshin49** [Jawbone/JBChartView#212]
When I tried to integrate JBChart to my Swift 2 app as the following:
```Swift

class ViewController: UIViewController, JBBarChartViewDelegate, JBBarChartViewDataSource 
{
...

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let barChartView = JBBarChartView();
        barChartView.dataSource = self;
        barChartView.delegate = self;
        barChartView.backgroundColor = UIColor.darkGrayColor();
        barChartView.frame = CGRectMake(0, 20, self.view.bounds.width, self.view.bounds.height * 0.5);
        barChartView.reloadData();
        self.view.addSubview(barChartView);
    }
...
}
```

I receive the following errors:
ViewController.swift:11:7: Type 'ViewController' does not conform to protocol 'JBBarChartViewDataSource'
ViewController.swift:11:7: Type 'ViewController' does not conform to protocol 'JBBarChartViewDelegate'

Sorry for the noob question, but I am new to Swift and iOS, and never used JBChart either.

FYI, here is the bridging header:
```Objective-C
#import "CVWrapper.h"
#import <UIKit/UIKit.h>
#import "JBChartView.h"
#import "JBBarChartView.h"
#import "JBLineChartView.h"
```

**Comment by terryworona** [comment]
Your controller must implement the required **datasource** and **delegate** functions as outlined in the JBBarChartView.h documentation. 

To read more about datasource and delegate patterns, as outlined by Apple, see see [here](https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaEncyclopedia/DelegatesandDataSources/DelegatesandDataSources.html).
