### ISSUE TITLE
JBBarChartView & Auto-layout

### ISSUE THREAD

**Issue by williamsjj** [Jawbone/JBChartView#213]
Is it possible to size JBBarChartView with auto layout constraints rather than manually setting the frame? The rest of our views are using auto-layout.

**Comment by terryworona** [comment]
A JB*ChartView is nothing more than a UIView subclass. As long as the layout constraints are applied to to the view, and then reloadData is called, everything should be a-ok. 

We (ie. Jawbone) use auto layout all the time with our JBChartView's with no issues.

**Comment by williamsjj** [comment]
Awesome. Using it in a UITableViewCell, so wired up .reloadData() into an override of layoutSubviews().
