### ISSUE TITLE
[question] Possible to disable vertical scrolling while thumbing horizontally over the line chart?

### ISSUE THREAD

**Issue by nate50** [Jawbone/JBChartView#215]
I have a line chart at the top of my screen, and then a number of other items below it that the user can scroll to. The line chart and the extra items are all embedded in a scroll view. The issue i'm having is that when the user thumbs over the chart to reveal the tooltip, its very sensitive to any vertical directional swiping, and results in canceling the tooltip and trying to scroll vertically at any slight diagonal swipe across the chart.

Once the user begins thumbing horizontally over the chart, is it possible to disable the vertical scroll feature, so that the user can only do one or the other at one time?

**Comment by terryworona** [comment]
Yes, it's possible to fix. 

Implement:

    - (void)lineChartView:(JBLineChartView *)lineChartView didSelectLineAtIndex:(NSUInteger)lineIndex horizontalIndex:(NSUInteger)horizontalIndex
    {
        self.scrollView.scrollingEnabled = NO;
    }

    - (void)didDeselectLineInLineChartView:(JBLineChartView *)lineChartView
    {
        self.scrollView.scrollingEnabled = YES;
    }
