### ISSUE TITLE
how to create a X-Axis and Y-Axis

### ISSUE THREAD

**Issue by saied685** [Jawbone/JBChartView#218]
how to create a X-Axis and Y-Axis for this sample?
i index a simple project

[ChartMe.zip](https://github.com/Jawbone/JBChartView/files/546381/ChartMe.zip)

thanks

**Comment by terryworona** [comment]
This issue has been asked before. 

It's not currently possible, but it's a feature I'd like to add sometime in the future.

If you can't wait, you can simply create a subview representing the x,y axis visuals and insert it below a transparent chart view.

More [here](https://github.com/Jawbone/JBChartView/issues/20#issuecomment-248878089).
