### ISSUE TITLE
Amazing issue with width of JBLineChartView

### ISSUE THREAD

**Issue by dsenash** [Jawbone/JBChartView#220]
Hi, I got amazing issue and I don't have ideas how to fix it.
It is loaded graph. You can see it doesn't fill all width of view.
![issue_orig](https://cloud.githubusercontent.com/assets/9079796/22176728/a2699ff6-e021-11e6-9113-dc3fd0bf6847.png)

If I load another data to graph then LineChartView is correct.

![issue_1](https://cloud.githubusercontent.com/assets/9079796/22176744/e55405e0-e021-11e6-905f-a893cb9a7f79.png)

If I load the same as first time data again then I got normal graph with full width.

![issue_2](https://cloud.githubusercontent.com/assets/9079796/22176853/cdca21be-e023-11e6-9912-a9ffe32999cc.png)

Original code and refreshed code by picker are the same.

    override func viewDidLoad() {
        super.viewDidLoad()
        pickerView.delegate = self
        pickerView.dataSource = self
        lineChartView.delegate = self;
        lineChartView.dataSource = self;
        showGraph()
    }

    func horizontalPickerView(_ pickerView: HorizontalPickerView, didSelectRow row: Int) {
        horizontalMarker = row
        showGraph()
   }

Additional code is:

   open func numberOfLines(in lineChartView: JBLineChartView!) -> UInt {
        return 1
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, numberOfVerticalValuesAtLineIndex lineIndex: UInt) -> UInt {
        return UInt(DataArrayNew.count )
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, verticalValueForHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> CGFloat {
        if (lineIndex == 0) {
            if DataArrayNew[Int(horizontalIndex)] < 0 {
                return 0
            }
            else {
                return CGFloat(DataArrayNew[Int(horizontalIndex)])
            }
        }
        else {
            return 0
        }
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, widthForLineAtLineIndex lineIndex: UInt) -> CGFloat {
        return 2.0
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, colorForLineAtLineIndex lineIndex: UInt) -> UIColor! {
        return UIColor.init(red: 127/255.0, green: 127/255.0, blue: 127/255.0, alpha: 1.0)
    }
    func lineChartView(_ lineChartView: JBLineChartView!, colorForDotAtHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> UIColor! {
        return UIColor.black
    }
    
    open func verticalSelectionWidth(for lineChartView: JBLineChartView!) -> CGFloat {
        return 1.0;
    }
    
    
    func lineChartView(_ lineChartView: JBLineChartView!, dotRadiusForDotAtHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> CGFloat {
        return CGFloat(25)
    }
    
    
    
    func lineChartView(_ lineChartView: JBLineChartView!, smoothLineAtLineIndex lineIndex: UInt) -> Bool {
        return true
    }
    
    func lineChartView(_ lineChartView: JBLineChartView!, selectionColorForLineAtLineIndex lineIndex: UInt) -> UIColor {
        return UIColor.init(red: 128/255.0, green: 128/255.0, blue: 128/255.0, alpha: 1.0)
    }
    
    
    
    func lineChartView(_ lineChartView: JBLineChartView!, didSelectLineAt lineIndex: UInt, horizontalIndex: UInt) {
        if (lineIndex == 0) && (Int(horizontalIndex) > 0) {
            let data = DataArray[Int(horizontalIndex) * 3 - 1]
            graphLbl.text = TimeArrayNew[Int(horizontalIndex)] + " " + NSLocalizedString("Temp: ", comment: "Температура: ") + data.fractionDigits(digits: 2) + "\u{00B0}C"
            
            
        }
    }

My mind is crashed. Why it is so?
Rg, Dmitry

**Comment by terryworona** [comment]
What's the frame of the graph on loadView?

**Comment by dsenash** [comment]
Frame is based on storyboard. I didn't set it specially.
LineChartView is under View and by constrains it has the same width and height always.
![issue_3](https://cloud.githubusercontent.com/assets/9079796/22176921/55ec0034-e025-11e6-8b22-a99bf7f5bbf1.png)

**Comment by terryworona** [comment]
Where are you calling reloadData on the graph?

Print out the frame of the chart on each subsequent call to reloadData to see if it's changing.

**Comment by dsenash** [comment]
It is func for reloading.   
 func showGraph() {
        //print("HistoricalDataNew> \(DataArrayNew.count)")
        //print("HistoricalData> \(DataArray.count)")
        //print("HistoricalTime> \(TimeArrayNew.count)")
        var max = maxElement(graph: DataArrayNew)
        if !(max > 0) {
            max = 1
        }
        _ = NarodMon.sharedInstance.getHistoricalData(interval: horizontalMarker, device:  sensorID)
        DataArrayNew = (NarodMon.sharedInstance.getDataArray() as NSArray) as! [Double]
        TimeArrayNew = (NarodMon.sharedInstance.getTimeArray() as NSArray) as! [String]
        DataArray = (NarodMon.sharedInstance.getDataArrayOrig() as NSArray) as! [Double]
        lineChartView.maximumValue = CGFloat(max)
        lineChartView.reloadData()
    }

It is first loading.
    override func viewDidLoad() {
        super.viewDidLoad()
        pickerView.delegate = self
        pickerView.dataSource = self
        lineChartView.delegate = self;
        lineChartView.dataSource = self;

        self.configureView()
        showGraph()
    }

It is refresh of graph.
    func horizontalPickerView(_ pickerView: HorizontalPickerView, didSelectRow row: Int) {
        horizontalMarker = row
        showGraph()
    }

frame - Ok. I'll try

**Comment by dsenash** [comment]
Hi, Yes. You are right. The frame was changes for some unknown reasons. It was different for first load and for others.
As soon as I fixed it and the issue was fixed.
Thanks so much.
Rg, Dmitry

**Comment by terryworona** [comment]
Cool! Glad it works.
