### ISSUE TITLE
selectionColorForDotAtHorizontalIndex doesn't change color

### ISSUE THREAD

**Issue by dsenash** [Jawbone/JBChartView#221]
Hello,
I like JBChartView but I am not so familiar with JBChartView and I am sorry if I am doing some misunderstanding or mistakes.
I'll happy if it is just my own mistake.
So. I read a lot of info about JBChartView and my current opinion selectionColorForDotAtHorizontalIndex color doesn't work.
I need to change vertical line for selection from default white to black because my background is white.
See screenshot below. It is screenshot during state of selection. I marked by red line place of selection. We can see line is white.
![issue_4](https://cloud.githubusercontent.com/assets/9079796/22185513/4ad9a024-e0f8-11e6-837e-89b5085b59b0.png)

Here is my code. 

func lineChartView(_ lineChartView: JBLineChartView!, selectionColorForDotAtHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> UIColor! {
        return UIColor.red
    }

I tried to do red and green just for testing. Actually it should be black.

Below is full set of code. 

 open func numberOfLines(in lineChartView: JBLineChartView!) -> UInt {
        return 1
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, numberOfVerticalValuesAtLineIndex lineIndex: UInt) -> UInt {
        return UInt(DataArrayNew.count )
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, verticalValueForHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> CGFloat {
        if (lineIndex == 0) {
            if DataArrayNew[Int(horizontalIndex)] < 0 {
                return 0
            }
            else {
                return CGFloat(DataArrayNew[Int(horizontalIndex)])
            }
        }
        else {
            return 0
        }
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, widthForLineAtLineIndex lineIndex: UInt) -> CGFloat {
        return 2.0
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, colorForLineAtLineIndex lineIndex: UInt) -> UIColor! {
        return UIColor.init(red: 128/255.0, green: 128/255.0, blue: 128/255.0, alpha: 1.0)
    }
    
    func lineChartView(_ lineChartView: JBLineChartView!, colorForDotAtHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> UIColor! {
        return UIColor.green
    }
    
    func lineChartView(_ lineChartView: JBLineChartView!, selectionColorForDotAtHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> UIColor! {
        return UIColor.red
    }
    
    open func verticalSelectionWidth(for lineChartView: JBLineChartView!) -> CGFloat {
        return 1.0;
    }
    
    func lineChartView(_ lineChartView: JBLineChartView!, lineStyleForLineAtLineIndex lineIndex: UInt) -> UInt {
        return 0
    }
    
    
    
    func lineChartView(_ lineChartView: JBLineChartView!, dotRadiusForDotAtHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> CGFloat {
        return CGFloat(25)
    }
    
    
    
    func lineChartView(_ lineChartView: JBLineChartView!, smoothLineAtLineIndex lineIndex: UInt) -> Bool {
        return true
    }
    
    func lineChartView(_ lineChartView: JBLineChartView!, selectionColorForLineAtLineIndex lineIndex: UInt) -> UIColor {
        return UIColor.init(red: 204/255.0, green: 204/255.0, blue: 204/255.0, alpha: 1.0)
    }
    
    func lineChartView(_ lineChartView: JBLineChartView!, verticalSelectionColorForLineAtLineIndex lineIndex: UInt) -> UIColor {
        return UIColor.black
    }
    
    func lineChartView(_ lineChartView: JBLineChartView!, verticalSelectionWidthForLineChartView
 lineIndex: UInt) -> CGFloat {
        return 2.0
    }
    
    
    func lineChartView(_ lineChartView: JBLineChartView!, didSelectLineAt lineIndex: UInt, horizontalIndex: UInt) {
        if (lineIndex == 0) && (Int(horizontalIndex) > 0) {
            let data = DataArray[Int(horizontalIndex) * 3 - 1]
            graphLbl.text = TimeArrayNew[Int(horizontalIndex)] + " " + NSLocalizedString("Temp: ", comment: "Температура: ") + data.fractionDigits(digits: 2) + "\u{00B0}C"
                     
        }
    }

Any ideas how to fix this?
Rg, Dmitry

**Comment by terryworona** [comment]
By default, dots aren't shown on a line chart. Try implementing: 

`
- (BOOL)lineChartView:(JBLineChartView *)lineChartView showsDotsForLineAtLineIndex:(NSUInteger)lineIndex
{
    return YES;
}
`

Hope this helps.

**Comment by dsenash** [comment]
Hi Terry, No. You haven't understood my points.
Changing of color for vertical line during selection doesn't work.
