### ISSUE TITLE
X,Y position of dot in LineChart

### ISSUE THREAD

**Issue by ZuzanaBenicko** [Jawbone/JBChartView#222]
Iam sorry this is more question than issue. Iam using your LineChartView but I need to alter the dot which is in it for another dot picture(and also get there vertical line in this position) Is there a way how to get the x and y position of dot in LineChart?

**Comment by ZuzanaBenicko** [comment]
I'm sorry for mistake in Title there should be DOT.

**Comment by terryworona** [comment]
The dot positions (ie. CGPoint) are not exposed through any public interface. 

What exactly are you trying to do? Any diagrams or code would help as well.

**Comment by ZuzanaBenicko** [comment]
What I would like to do is alter dot for something like this. 

![linechart](https://cloud.githubusercontent.com/assets/9416708/22326588/a1e0554e-e3b3-11e6-9124-7e30d5e67f1b.jpg)

**Comment by terryworona** [comment]
It's is not possible to get an (x,y) position of a dot while scrubbing. 

The code is open source, so you could presumably create a delegate callback:

```
- (UIView *)didSelectDotAtIndex:(NSUInteger)lineIndex horizontalIndex:(NSUInteger)horizontalIndex;
```

Take a peak at `touchesBeganOrMovedWithTouches` to see how we do this for line selections. 

I would suggest forking the library and make the appropriate changes.

Closing issue.
