### ISSUE TITLE
Customization of JBLineChart doesn't work

### ISSUE THREAD

**Issue by dsenash** [Jawbone/JBChartView#224]
Hi,
I am trying to do customization of colors for lineChartView but it doesn't work.
My application is in white/black style.
I am trying to show point of selection of somehow but any customization functions don't work.
I don't know why. My be I have limited quantity of libraries?
It is unselected state:
![jblinechart1](https://cloud.githubusercontent.com/assets/9079796/22733993/214251ec-ee05-11e6-9e67-7dcf4f315e78.png)

It is selected state:
![jblinechart2](https://cloud.githubusercontent.com/assets/9079796/22734011/2e00abfe-ee05-11e6-9275-0355c780d552.png)

But my code specially has a lot of colors:

  open func numberOfLines(in lineChartView: JBLineChartView!) -> UInt {
        return 1
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, numberOfVerticalValuesAtLineIndex lineIndex: UInt) -> UInt {
        //print("VerticalIndex>\(DataArrayNew.count)")
        return UInt(DataArrayNew.count )
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, verticalValueForHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> CGFloat {
        if (lineIndex == 0) {
            //print("LineIndex> \(CGFloat(DataArrayNew[Int(horizontalIndex)]))")
            if DataArrayNew[Int(horizontalIndex)] < 0 {
                return 0
            }
            else {
                return CGFloat(DataArrayNew[Int(horizontalIndex)])
            }
        }
        else {
            return 0
        }
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, widthForLineAtLineIndex lineIndex: UInt) -> CGFloat {
        return 2.0
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, colorForLineAtLineIndex lineIndex: UInt) -> UIColor! {
        return UIColor.init(red: 128/255.0, green: 128/255.0, blue: 128/255.0, alpha: 1.0)
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, colorForDotAtHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> UIColor! {
        return UIColor.lightGray
    }
    
    
    open func verticalSelectionWidth(for lineChartView: JBLineChartView!) -> CGFloat {
        return 1.0;
    }
    
    
    
    open func lineChartView(_ lineChartView: JBLineChartView!, dotRadiusForDotAtHorizontalIndex horizontalIndex: UInt, atLineIndex lineIndex: UInt) -> CGFloat {
        return CGFloat(25)
    }
    
    
    
    open func lineChartView(_ lineChartView: JBLineChartView!, smoothLineAtLineIndex lineIndex: UInt) -> Bool {
        return true
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, selectionColorForLineAtLineIndex lineIndex: UInt) -> UIColor {
        return UIColor.lightGray
    }
    
    func lineChartView(_ lineChartView: JBLineChartView!, verticalSelectionColorForLineAtLineIndex lineIndex: UInt) -> UIColor {
        return UIColor.red
    }
    
    
    
    open func lineChartView(_ lineChartView: JBLineChartView!, selectionGradientForLineAtLineIndex lineIndex: UInt) -> CAGradientLayer {
        let topColor = UIColor.red
        let bottomColor = UIColor.green
        
        let gradientColors: [CGColor] = [topColor.cgColor, bottomColor.cgColor]
        let gradientLocations: [Float] = [0.0, 1.0]
        
        let gradientLayer: CAGradientLayer = CAGradientLayer()
        gradientLayer.colors = gradientColors
        gradientLayer.locations = gradientLocations as [NSNumber]?
        
        return gradientLayer
    }
    
    open func lineChartView(_ lineChartView: JBLineChartView!, selectionFillGradientForLineAtLineIndex lineIndex: UInt) -> CAGradientLayer {
        let topColor = UIColor.orange
        let bottomColor = UIColor.blue
        
        let gradientColors: [CGColor] = [topColor.cgColor, bottomColor.cgColor]
        let gradientLocations: [Float] = [0.0, 1.0]
        
        let gradientLayer: CAGradientLayer = CAGradientLayer()
        gradientLayer.colors = gradientColors
        gradientLayer.locations = gradientLocations as [NSNumber]?
        
        return gradientLayer
    }
 
    open func lineChartView(_ lineChartView: JBLineChartView!, verticalSelectionWidthForLineChartView
 lineIndex: UInt) -> CGFloat {
        return 5.0
    }
    open func didDeselectLineInLineChartView(for lineChartView: JBLineChartView!) {
        print("deselect")
    }

    
    func lineChartView(_ lineChartView: JBLineChartView!, didSelectLineAt lineIndex: UInt, horizontalIndex: UInt) {
        //lineChartView.backgroundColor = UIColor.init(red: 204/255.0, green: 204/255.0, blue: 204/255.0, alpha: 1.0)
        if (lineIndex == 0) && (Int(horizontalIndex) > 0) {
            let data = DataArray[Int(horizontalIndex) * 3 - 1]
            //print (TimeArrayNew[Int(horizontalIndex)])
            
                 graphLbl.text = TimeArrayNew[Int(horizontalIndex)] +  "Value: " + data.fractionDigits(digits: 0) + " " + sensorUnit
         }
    }
 
I use in my project the following libraries:
![jblinechart3](https://cloud.githubusercontent.com/assets/9079796/22735323/3202d330-ee0a-11e6-971e-50866a5273de.png)

I'll very appreciate for any advice how to fix this.
Rg, Dmitry

**Comment by dsenash** [comment]
You can see I specially added red/yellow/green colors to code. But looks like customization of colors doesn't work completely.
I think possible something is absent at libraries.
Rg, Dmitry

**Comment by terryworona** [comment]
Can you elaborate on what exactly you are trying to customize? Your datasource/delegate has a mixture of functions that are conflicting. 

Do you want grey/white lines? Gradient fills? Dots? 

The question you are asking is too broad. Perhaps a mock-up image of what you're trying to achieve will help me address the issue you are having.

**Comment by dsenash** [comment]
I want just vertical line during selection mode to do black. My background is white. The style of app is white. But default color of selectionVertical line is white and I can't change it to black.

**Comment by dsenash** [comment]
I configured it as red but it is still white.
func lineChartView(_ lineChartView: JBLineChartView!, verticalSelectionColorForLineAtLineIndex lineIndex: UInt) -> UIColor {
    return UIColor.red
}

I tried to change background to other during selection or find any other workaround and found that gradient doesn't work as well.

**Comment by terryworona** [comment]
You've declared `verticalSelectionWidth` twice; remove the latter one. 

I've taken your code (minus the redeclaration of `verticalSelectionWidth`) and integrated it into the demo project & everything works fine. 

Hope this helps. 

![screen shot 2017-02-08 at 1 58 46 pm](https://cloud.githubusercontent.com/assets/358709/22759330/eaaeeaf8-ee06-11e6-809e-2843b173f0aa.png)
