### ISSUE TITLE
The Width of the line getting decreasing if number of lines count increases in JBBarChartView

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [Jawbone/JBChartView#236]
Thanks for the great library, its helped us so much for graph. Following Graph we have used.

https://github.com/Jawbone/JBChartView

And We are using JBBarChartView in this library.

We have got one issue.

Issue : I am passing Array of data to show the number of lines into that graph. So if Array count is greater than 100, its coming lines are very less width even some times not able to visible.

If Array count is 50 or 60 its coming good.
I understand its taking by number of lines and adjusting the width of every line (bar)

**Where can I change for this, I want same width for all data.**

I got struck due to this from 2 days.

Can you please help us to fix this?

**And is there possibility to set 3 colours for each bar?**

**And initial time even if I assign 30 indexes with Array with 0 (zero), its showing full lines with big height even I set minimum value is 0.0f?**

PFA.
![screen shot 2017-12-11 at 6 33 00 pm](https://user-images.githubusercontent.com/8393997/33832569-aa2cbfcc-dea2-11e7-8e85-5788f64fe2cc.png)

![screen shot 2017-12-11 at 6 33 15 pm](https://user-images.githubusercontent.com/8393997/33832571-aa5f4fd2-dea2-11e7-9f6a-94ebc4fe2335.png)
![screen shot 2017-12-11 at 6 47 02 pm](https://user-images.githubusercontent.com/8393997/33832939-e80c6c1a-dea3-11e7-9a3e-9d8885500a3d.png)

**Comment by terryworona** [comment]
Please see the [performance](https://github.com/Jawbone/JBChartView#performance) section of the Wiki. 

"For large datasets, we recommend that your dataSource to supply a subset of points; clustering those that are close to one another."
