### ISSUE TITLE
JBChartView and Swift

### ISSUE THREAD

**Issue by Dirk23** [Jawbone/JBChartView#240]
Hi,

i just wanted to add JBChartView to my Project and installed it via Cocoapods. I already had a bridging header file in my project for fmdb (sqlite class). After installation i added the missing lines to the bridging header:
```
#import "JBChartView.h"
#import "JBBarChartView.h"
#import "JBLineChartView.h"
```
i already had `#import <UIKit/UIKit.h>` in the bridging header file for fmdb. But after compiling the project Xcode complains about all .h files for JBChartView wich can not be found.

<img width="1030" alt="bildschirmfoto 2018-07-10 um 20 55 26" src="https://user-images.githubusercontent.com/4200682/42531191-a498bbba-8483-11e8-8879-109ed498dfd7.png">

What do i need to do here?

Regards

Dirk

**Comment by zadr** [comment]
You'll want to import with framework search paths using angular brackets, e.g.: <JBChartView/JBChartView.h>

**Comment by Dirk23** [comment]
Sadly, that didn't help. Still an error Message, but a bit different:"<JBChartView/JBChartView.h>' file not found"

**Comment by Dirk23** [comment]
Thank you @zadr that helped (after I removed the "" around the <JBChartView/JBChartView.h>)
