### ISSUE TITLE
Problem with Bar Height

### ISSUE THREAD

**Issue by meduza** [Jawbone/JBChartView#28]
I followed the tutorial and had a problem with bar height. Every time one bar has zero height (not showing in a view).

This is my code:
- (void)viewDidLoad
  {
  [super viewDidLoad];
  // data array
  _data = @[@20, @30, @50];
  
  JBBarChartView *barChartView = [[JBBarChartView alloc] init];
  barChartView.delegate = self;
  barChartView.dataSource = self;
  barChartView.frame = CGRectMake(20, 120, 280, 200);
  barChartView.autoresizingMask = UIViewAutoresizingFlexibleWidth;
  barChartView.layer.borderWidth = 1;
  [self.view addSubview:barChartView];
  
  [barChartView reloadData];
  }
- (NSUInteger)numberOfBarsInBarChartView:(JBBarChartView *)barChartView{
  NSLog(@"numberOfBarsInBarChartView: %lu", (unsigned long)[self.data count]);
  return [self.data count];
  }
- (CGFloat)barChartView:(JBBarChartView *)barChartView heightForBarViewAtAtIndex:(NSUInteger)index{
  NSLog(@"heightForBarViewAtAtIndex: %lu, height: %f", index, [[self.data objectAtIndex:index] floatValue]);
  return [[self.data objectAtIndex:index] floatValue];
  }

Debug log:

12:51:55.054 App[5116:60b] numberOfBarsInBarChartView: 3
12:51:55.055 App[5116:60b] heightForBarViewAtAtIndex: 0, height: 20.000000
12:51:55.056 App[5116:60b] heightForBarViewAtAtIndex: 1, height: 30.000000
12:51:55.057 App[5116:60b] heightForBarViewAtAtIndex: 2, height: 50.000000

![bar-image](https://cloud.githubusercontent.com/assets/16512/2629051/2d84dfd4-be32-11e3-99b6-4db7d31ee002.png)

**Comment by AnilkumarRabhasa** [comment]
Can you please give suggestions to this issue.

https://github.com/Jawbone/JBChartView/issues/236
