### ISSUE TITLE
Add bar/line caching for only visible content. 

### ISSUE THREAD

**Issue by Zatoichy** [Jawbone/JBChartView#61]
Table method is called for 'view' (barChartView: barViewAtIndex:) only visible cells. Currently data is loaded completely. Because it requires a lot of memory.

JBBarChartView -> UIView -> UIScrollView

Succinctly:
JBBarChartView *jbChartView = [[JBBarChartView alloc] init];
UIView *chartView = [[UIView alloc] init];
[chartView addSubview:jbChartView];
UIScrollView *chartScrollView = [[UIView alloc] init];
[chartScrollView addSubview:chartView];

**Comment by khoogheem** [comment]
The ability to scroll would be great!!!  Looking at using this to show live data.. so the concept of scrolling would be nice to have

**Comment by terryworona** [comment]
It's unlikely this will become a reality. The chart simply wasn't intended to show a live stream of (scrollable) data. Much of the underlying architecture would need to be changed. 

We haven't had a lot of requests for this functionality, so until we get more, I'm going to curb this request.
