### ISSUE TITLE
Straight lines

### ISSUE THREAD

**Issue by simonbromberg** [Jawbone/JBChartView#94]
In the screenshot below the points have been given vertical values that incremented by 5 (e.g. 0,5,10...)

As you can see, the last one is slightly askew and so the line is not straight

I printed out the y-offsets and got the following 0,22,45,68,90,112
Some of these are increments of 22 and some are increments of 23.

![ios simulator screen shot aug 24 2014 3 50 00 pm](https://cloud.githubusercontent.com/assets/2942298/4024423/49f7797a-2bc8-11e4-9040-6ee0736e5763.png)

**Comment by terryworona** [comment]
It appears that the line width /2 is subtracted from both the max Y and min Y. 

This issue only applies to linear lines that approach the max or min Y values of the chart. It will cause the slope of the line to be modified a factor of half the line's width. 

Example:

    {3, 132}
    {52, 112.5} -> [49, 19.5]
    {101, 90} -> [49, 22.5]
    {150, 67.5} -> [49, 22.5]
    {199, 45} -> [49, 22.5]
    {248, 22.5} -> [49, 22.5]
    {297, 3} -> [49, 19.5]

Delta's are in " [ ] ". Notice teh top and bottom deltas are 19.5, while the middle deltas are all 22.5.

**Comment by terryworona** [comment]
One such solution is to add half of the chart's max line width to the internal min and max values.

**Comment by terryworona** [comment]
Fixed via commit: 9828034f6bd95f1ca26f8d79d1707d0ea2bb0c52

Screenshot attached. 

Thanks for patience! 

![screen shot 2015-11-22 at 6 52 34 pm](https://cloud.githubusercontent.com/assets/358709/11329026/49c0c0ae-914a-11e5-9a9b-6736d9d35847.png)
